server:
  port: 9999
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.87.154:3306/mybs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: '123456'
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
    #mybatis配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.springbootpro.entity
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#打印sql
logging:
  level:
    com.example.springbootpro.mapper : debug